version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.eForm
    versions:
    - 4.3.14
    - 4.3.17
    - 4.3.18
    - 4.4.22
  - dependency-name: Microsoft.Extensions.Localization
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Identity.UI
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
